ROWS_NUM, COLS_NUM = 8, 8
SQUARE_SIZE = 80

BOARD_WIDTH = BOARD_HEIGHT = SQUARE_SIZE * ROWS_NUM

PIECE_WIDTH = PIECE_HIGHT = 110
PIECE_SIZE = (PIECE_WIDTH, PIECE_HIGHT)

FPS = 60

AI_ENGINE_DEPTH = 1

PIECE_PADDING = 12